Finished
TheCSharpAcademy/CodeReviews.Console.CodingTracker pull request #134
Opened 2024-09-14 21:57 UTC by JvR-Hannes

2024-09-20 11:57 UTC, chrisjamiecarter requested changes
Please make changes as per comment.

2024-09-20 11:57 UTC, chrisjamiecarter commented on README.md
Hey @JvR-Hannes 👋 ,

Could you move this file into your project folder please?

NOTE: You already have a README.md in you project folder, but it is empty. So maybe copy/paste contents and then delete this file?

Either way, once done: commit and push the change (which will update this PR).

I will then begin my review.

Thanks
@chrisjamiecarter

2024-09-21 09:38 UTC, chrisjamiecarter requested changes
Hey @JvR-Hannes,

Unfortunately I have found a couple of bugs in your code...

When viewing all records on a new database...

![image](https://github.com/user-attachments/assets/6a2064a8-ed29-423f-a44f-70774bcfe6d7)

I can workaround by adding a record. But this needs fixing as it fails the requirement carried over from [habit-logger](https://thecsharpacademy.com/project/12/habit-logger):
- [ ]  You should handle all possible errors so that the application never crashes.


You are currently failing the [requirement](https://thecsharpacademy.com/project/13/coding-tracker):

- [ ]  You should tell the user the specific format you want the date and time to be logged and not allow any other format.

If you are requesting `yyyy-MM-dd HH:mm:ss` you should only accept this. Read up on TryParseExact

![image](https://github.com/user-attachments/assets/7ccb59c2-67e2-426f-9a24-10af1f9499f9)


See the [tips section](https://thecsharpacademy.com/project/13/coding-tracker):

- Don't forget the user input's validation: Check for incorrect dates. What happens if a menu option is chosen that's not available? What happens if the users input a string instead of a number? **Remember that the end date can't be before the start date**.

Currently you allow the end date to be before the start date.

![image](https://github.com/user-attachments/assets/dc094234-dd88-4efa-85d5-db986bbf4a75)

Please could you fix, let me know if you need any support.

Don't be disheartened, the project is nearly complete! Just a few issue to iron out!

Thanks
@chrisjamiecarter

2024-09-21 11:56 UTC, JvR-Hannes commented
Ok, I'll check it out, looks like I didn't add a closing tag there, will
fix and update repo

On Sat, 21 Sept 2024, 11:38 Chris Carter, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey @JvR-Hannes <https://github.com/JvR-Hannes>,
>
> Unfortunately I have found a bug in your code...
>
> When viewing all records on a new database...
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/6a2064a8-ed29-423f-a44f-70774bcfe6d7>
>
> I can workaround by adding a record. But this needs fixing as it fails the
> requirement carried over from habit-logger
> <https://thecsharpacademy.com/project/12/habit-logger>:
>
>    - You should handle all possible errors so that the application never
>    crashes.
>
> Please could you fix, let me know if you need any support.
>
> Thanks
> @chrisjamiecarter <https://github.com/chrisjamiecarter>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/134#pullrequestreview-2319700966>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A62U75X3XISKNV45KMA3SCTZXU5BHAVCNFSM6AAAAABOHGEZH2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMJZG4YDAOJWGY>
> .
> You are receiving this because you were mentioned.Message ID:
> <TheCSharpAcademy/CodeReviews.Console.
> ***@***.***>
>

2024-09-21 12:01 UTC, chrisjamiecarter commented
Also. I am not sure and am checking. But I think you also need to provide an update method.

So you can create, read, update and delete a coding session.

Apologies I didn't add to the previous comment.

2024-09-21 15:35 UTC, JvR-Hannes commented
Ok yeah, I saw that I completely missed it, I'm not sure what happened that
make me miss it. I have added it and also the closing tag on the no records
found.

Thanks for letting me know

On Sat, 21 Sept 2024, 14:01 Chris Carter, ***@***.***> wrote:

> Also. I am not sure and am checking. But I think you also need to provide
> an update method.
>
> So you can create, read, update and delete a coding session.
>
> Apologies I didn't add to the previous comment.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/134#issuecomment-2365161086>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A62U75SOGTOF26T3U45HOTTZXVNZLAVCNFSM6AAAAABOHGEZH2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNRVGE3DCMBYGY>
> .
> You are receiving this because you were mentioned.Message ID:
> <TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/134/c2365161086@
> github.com>
>

2024-09-23 13:40 UTC, chrisjamiecarter approved these changes
Well done @JvR-Hannes on another complete project 🎉

2024-09-23 13:40 UTC, closed without merging