I finsh the project
TheCSharpAcademy/CodeReviews.Console.CodingTracker pull request #144
Opened 2024-10-11 10:04 UTC by nikosnick13

I finished the project. it was so much fun.
I would like if you could direct me to the specter console tips. Please be brutal in code review!!!!

2024-10-11 15:08 UTC, chrisjamiecarter requested changes
Hey @nikosnick13  👋,

First off, excellent work on another application! 🎉 It’s great to see your progress.

I have performed a peer review and your code is structured well and uses Spectre.Console effectively for a user-friendly console application. 

However, unfortunately you have missed a few requirements:
- [ ] Your project needs to contain a Read Me file where you'll explain how your app works. **(NOTE: This application has the same base requirements as the habit tracker.)**
- [ ] You're required to have separate classes in different files (ex. `UserInput.cs`, `Validation.cs`, `CodingController.cs`) **(NOTE: Validation logic seems to be mixed in everywhere instead of its own file)**
- [ ] You'll need to create a "CodingSession" class in a separate file. It will contain the properties of your coding session: Id, StartTime, EndTime, Duration. **(NOTE: you have one Date property and are missing the time components)**
- [ ] The user shouldn't input the duration of the session. It should be calculated based on the Start and End times, in a separate "CalculateDuration" method. **(NOTE: you are prompting the user for a duration)**
- [ ] The user should be able to input the start and end times manually. (NOTE: User can only enter Date, not start time and end time)
- [ ] You need to use Dapper ORM for the data access instead of ADO.NET. **(NOTE: you are using ADO.NET)**
- [ ] Follow the [DRY Principle](https://thecsharpacademy.com/article/30006/dry-principle-csharp), and avoid code repetition. **(NOTE: The code for getting and validating the ID in both `ProcessDelete` and `ProcessEdit` is nearly identical. This can be refactored into a helper method like `GetValidId` to avoid duplication and make the code more maintainable.)**

Apologies this seems like a lot.

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points.

Thanks
@chrisjamiecarter

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/Coding.cs
> +﻿namespace Coding_Tracker.nikosnick13
As per the academy's [code-conventions](https://thecsharpacademy.com/article/58/code-conventions) - Use the newest namespaces.
Use file-scoped namespaces to save an indentation level:

❌ 
```
// Block-Scoped Namespace
namespace YourNamespace
{
    // ...
}
```

✔️ 
```
// File-Scoped Namespace
namespace YourNamespace;

// ...
```

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/CodingController.cs
> +
As per the academy's [code-conventions](https://thecsharpacademy.com/article/58/code-conventions) - Have one empty line between methods.

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/CodingController.cs
> +            using (var conn  = new SQLiteConnection(connectionString))
You can use the simpler "Using Declaration" syntax to save an indentation level against the "Using Statement" syntax:

❌ 
```
// Using Statement
using (var connection = new SqliteConnection(connectionString))
{
    // ...
}
```

✔️ 
```
// Using Declaration
using var connection = new SqliteConnection(connectionString);
// ...
```

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/CodingController.cs
> +                string query = @"INSERT INTO coding (Date, Duration) VALUES (@date, @dutation)";
There is a typo in the query, where you have @dutation instead of @duration.

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/CodingController.cs
> +                    insertCmd.Parameters.AddWithValue("date",coding.Date);
It's better practice to include the @ sign when naming SQL parameters inside the AddWithValue method to avoid any confusion, even though SQLite allows it without.

```
insertCmd.Parameters.AddWithValue("@date", coding.Date);
insertCmd.Parameters.AddWithValue("@duration", coding.Duration);
```

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/CodingController.cs
> +
As per the academy's [code-conventions](https://thecsharpacademy.com/article/58/code-conventions) - Remove empty lines after opening curly brackets and before closing curly brackets.

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/Program.cs
> +        //  static public string connectionString = ConfigurationManager.AppSettings.Get("ConnectionString");
As per the academy's [code-conventions](https://thecsharpacademy.com/article/58/code-conventions) - Remove unused code.

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/DatabaseManager.cs
Missing requirement:
- [ ] You need to use Dapper ORM for the data access instead of ADO.NET. (This requirement was included in Feb/2024)

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/CodingController.cs
Missing requirement:
- [ ] You need to use Dapper ORM for the data access instead of ADO.NET. (This requirement was included in Feb/2024)

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/Coding.cs
Missing requirement
- [ ] You'll need to create a "CodingSession" class in a separate file. It will contain the properties of your coding session: Id, StartTime, EndTime, Duration
- [ ] The user shouldn't input the duration of the session. It should be calculated based on the Start and End times, in a separate "CalculateDuration" method.

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/CodingController.cs
Method names like Post, Get, Delete, and Update could be more descriptive to clarify what kind of operations they are performing on Coding objects. For instance, you could use:

- `InsertCodingRecord`
- `GetAllCodingRecords`
- `UpdateCodingRecord`
- `DeleteCodingRecordById`

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/UserMenu.cs
There are multiple spelling mistakes in the code that affect readability. Here are the correct spellings:
- `ProssesAdd` → `ProcessAdd`
- `ProssesEdit` → `ProcessEdit`
- `isAppRuning` → `isAppRunning`
- `Dutation` → `Duration`
- `commantInput` → `commandInput`
- `manu` → `menu`

Fixing these will make the code cleaner and more professional.

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/UserMenu.cs
> +                ProcessDelete();
This will cause a recursive loop and needs re-work.

2024-10-11 15:08 UTC, chrisjamiecarter commented on Coding Tracker.nikosnick13/UserMenu.cs
> +                ProssesEdit();
This will cause a recursive loop and needs re-work.

2024-10-14 11:18 UTC, nikosnick13 commented
Hi Chris

to understand, the Coding class will become Season Coding, will it have  the following properties?

public int Id { get; set; }
public DateTime StartTime { get; set; }
public DateTime EndTime { get; set; }
public TimeSpan Duration { get; set; }
________________________________
From: Chris Carter ***@***.***>
Sent: Friday, October 11, 2024 3:09 PM
To: TheCSharpAcademy/CodeReviews.Console.CodingTracker ***@***.***>
Cc: nikosnick13 ***@***.***>; Mention ***@***.***>
Subject: Re: [TheCSharpAcademy/CodeReviews.Console.CodingTracker] I finsh the project (PR #144)


@chrisjamiecarter requested changes on this pull request.

Hey @nikosnick13<https://github.com/nikosnick13> 👋,

First off, excellent work on another application! 🎉 It’s great to see your progress.

I have performed a peer review and your code is structured well and uses Spectre.Console effectively for a user-friendly console application.

However, unfortunately you have missed a few requirements:

  *    Your project needs to contain a Read Me file where you'll explain how your app works. (NOTE: This application has the same base requirements as the habit tracker.)
  *    You're required to have separate classes in different files (ex. UserInput.cs, Validation.cs, CodingController.cs) (NOTE: Validation logic seems to be mixed in everywhere instead of its own file)
  *    You'll need to create a "CodingSession" class in a separate file. It will contain the properties of your coding session: Id, StartTime, EndTime, Duration. (NOTE: you have one Date property and are missing the time components)
  *    The user shouldn't input the duration of the session. It should be calculated based on the Start and End times, in a separate "CalculateDuration" method. (NOTE: you are prompting the user for a duration)
  *    The user should be able to input the start and end times manually. (NOTE: User can only enter Date, not start time and end time)
  *    You need to use Dapper ORM for the data access instead of ADO.NET. (NOTE: you are using ADO.NET)
  *    Follow the DRY Principle<https://thecsharpacademy.com/article/30006/dry-principle-csharp>, and avoid code repetition. (NOTE: The code for getting and validating the ID in both ProcessDelete and ProcessEdit is nearly identical. This can be refactored into a helper method like GetValidId to avoid duplication and make the code more maintainable.)

Apologies this seems like a lot.

Feel free to reach out if you have any questions or if you'd like to collaborate further on any of these points.

Thanks
@chrisjamiecarter<https://github.com/chrisjamiecarter>

________________________________

In Coding Tracker.nikosnick13/Coding.cs<https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/144#discussion_r1797059642>:

> @@ -0,0 +1,9 @@
+﻿namespace Coding_Tracker.nikosnick13


As per the academy's code-conventions<https://thecsharpacademy.com/article/58/code-conventions> - Use the newest namespaces.
Use file-scoped namespaces to save an indentation level:

❌

// Block-Scoped Namespace
namespace YourNamespace
{
    // ...
}


✔️

// File-Scoped Namespace
namespace YourNamespace;

// ...


________________________________

In Coding Tracker.nikosnick13/CodingController.cs<https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/144#discussion_r1797061065>:

> @@ -0,0 +1,150 @@
+﻿using Microsoft.Data.Sqlite;
+using Spectre.Console;
+using System.Configuration;
+using System.Data.SQLite;
+using static System.Console;
+using static System.Runtime.InteropServices.JavaScript.JSType;
+
+namespace Coding_Tracker.nikosnick13
+{
+    internal class CodingController
+    {
+        static public string connectionString = ConfigurationManager.AppSettings["ConnectionString"];
+
+


As per the academy's code-conventions<https://thecsharpacademy.com/article/58/code-conventions> - Have one empty line between methods.

________________________________

In Coding Tracker.nikosnick13/CodingController.cs<https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/144#discussion_r1797062683>:

> +using Spectre.Console;
+using System.Configuration;
+using System.Data.SQLite;
+using static System.Console;
+using static System.Runtime.InteropServices.JavaScript.JSType;
+
+namespace Coding_Tracker.nikosnick13
+{
+    internal class CodingController
+    {
+        static public string connectionString = ConfigurationManager.AppSettings["ConnectionString"];
+
+
+        public void Post(Coding coding)
+        {
+            using (var conn  = new SQLiteConnection(connectionString))


You can use the simpler "Using Declaration" syntax to save an indentation level against the "Using Statement" syntax:

❌

// Using Statement
using (var connection = new SqliteConnection(connectionString))
{
    // ...
}


✔️

// Using Declaration
using var connection = new SqliteConnection(connectionString);
// ...


________________________________

In Coding Tracker.nikosnick13/CodingController.cs<https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/144#discussion_r1797063571>:

> +using static System.Console;
+using static System.Runtime.InteropServices.JavaScript.JSType;
+
+namespace Coding_Tracker.nikosnick13
+{
+    internal class CodingController
+    {
+        static public string connectionString = ConfigurationManager.AppSettings["ConnectionString"];
+
+
+        public void Post(Coding coding)
+        {
+            using (var conn  = new SQLiteConnection(connectionString))
+            {
+                conn.Open();
+                string query = @"INSERT INTO coding (Date, Duration) VALUES ***@***.***, @dutation)";


There is a typo in the query, where you have @dutation instead of @duration<https://github.com/duration>.

________________________________

In Coding Tracker.nikosnick13/CodingController.cs<https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/144#discussion_r1797064215>:

> +    internal class CodingController
+    {
+        static public string connectionString = ConfigurationManager.AppSettings["ConnectionString"];
+
+
+        public void Post(Coding coding)
+        {
+            using (var conn  = new SQLiteConnection(connectionString))
+            {
+                conn.Open();
+                string query = @"INSERT INTO coding (Date, Duration) VALUES ***@***.***, @dutation)";
+
+                using (var insertCmd = new SQLiteCommand(query,conn))
+                {
+
+                    insertCmd.Parameters.AddWithValue("date",coding.Date);


It's better practice to include the @ sign when naming SQL parameters inside the AddWithValue method to avoid any confusion, even though SQLite allows it without.

***@***.***", coding.Date);
***@***.***", coding.Duration);


________________________________

In Coding Tracker.nikosnick13/CodingController.cs<https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/144#discussion_r1797064954>:

> +        public void Post(Coding coding)
+        {
+            using (var conn  = new SQLiteConnection(connectionString))
+            {
+                conn.Open();
+                string query = @"INSERT INTO coding (Date, Duration) VALUES ***@***.***, @dutation)";
+
+                using (var insertCmd = new SQLiteCommand(query,conn))
+                {
+
+                    insertCmd.Parameters.AddWithValue("date",coding.Date);
+                    insertCmd.Parameters.AddWithValue("dutation", coding.Duration);
+
+                    insertCmd.ExecuteNonQuery();
+                }
+


As per the academy's code-conventions<https://thecsharpacademy.com/article/58/code-conventions> - Remove empty lines after opening curly brackets and before closing curly brackets.

________________________________

In Coding Tracker.nikosnick13/Program.cs<https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/144#discussion_r1797067357>:

> @@ -0,0 +1,22 @@
+﻿using System.Configuration;
+
+namespace Coding [...]

2024-10-14 16:16 UTC, chrisjamiecarter commented
Hey @nikosnick13, I noticed you replied via email, try to view my comments on the github site. They should make more sense 💻 .

It is important that you digest and resolve all my points as this submission is missing a lot of requirements 📖 .

To clarify on your point (note: it should be `CodingSession` not `CodingSeason`), this class should definitely have the below as a minimum.

```
Id
StartTime
EndTime
Duration
```

The accessibility and types of these properties is up to you 🤔 .

The important bit is that `Duration` needs to be calculated before insertion into the database, and not captured as user input.

Thanks and good luck 🍀 ,
@chrisjamiecarter

2024-10-19 09:16 UTC, TheCSharpAcademy commented
@nikosnick13 Let us know if you need help 😁

2024-10-21 07:07 UTC, nikosnick13 commented
Hi Chris of course i will let you know get stack 😁😁
________________________________
From: The C# Academy ***@***.***>
Sent: Saturday, October 19, 2024 9:16 AM
To: TheCSharpAcademy/CodeReviews.Console.CodingTracker ***@***.***>
Cc: nikosnick13 ***@***.***>; Mention ***@***.***>
Subject: Re: [TheCSharpAcademy/CodeReviews.Console.CodingTracker] I finsh the project (PR #144)


@nikosnick13<https://github.com/nikosnick13> Let us know if you need help 😁

—
Reply to this email directly, view it on GitHub<https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/144#issuecomment-2423712750>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALSDISNNXKHSHO7QWLZH2VLZ4IPQBAVCNFSM6AAAAABPYS44T6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMRTG4YTENZVGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-28 06:35 UTC, TheCSharpAcademy commented
@nikosnick13 I saw you committed some changes. Did you address all issues? 😄

2024-10-31 05:52 UTC, TheCSharpAcademy commented
@nikosnick13  It's been two weeks since the suggested changes, so we're archiving this project. Feel free to reopen the PR and resubmit in the academy when you're ready. 🤓@chrisjamiecarter You'll get the points regardless.

2024-10-31 05:52 UTC, closed without merging

2024-10-31 07:48 UTC, nikosnick13 commented
Hi @chrisjamiecarter  sorry for the delay, I faced some issues with the project and rebuilt it again. 
It will take me a few days to finish it thank you for the guidance i will back to you soon. 
:)   :)

2024-11-08 07:59 UTC, nikosnick13 commented
Hi,

Sorry for my delait.   I submitted the project again.
https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/153

Thanks for your understanding. I waiting your review 🙂 🙂



________________________________
From: The C# Academy ***@***.***>
Sent: Thursday, October 31, 2024 5:52 AM
To: TheCSharpAcademy/CodeReviews.Console.CodingTracker ***@***.***>
Cc: nikosnick13 ***@***.***>; Mention ***@***.***>
Subject: Re: [TheCSharpAcademy/CodeReviews.Console.CodingTracker] I finsh the project (PR #144)


@nikosnick13<https://github.com/nikosnick13> It's been two weeks since the suggested changes, so we're archiving this project. Feel free to reopen the PR and resubmit in the academy when you're ready. ***@***.***<https://github.com/chrisjamiecarter> You'll get the points regardless.

—
Reply to this email directly, view it on GitHub<https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/pull/144#issuecomment-2449054722>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALSDISJCGLH4XBFOTPKJAELZ6HATHAVCNFSM6AAAAABPYS44T6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINBZGA2TINZSGI>.
You are receiving this because you were mentioned.Message ID: ***@***.***>