Add project for review
TheCSharpAcademy/CodeReviews.Console.CodingTracker pull request #2
Opened 2023-01-06 10:30 UTC by kimfom01

2023-01-06 19:11 UTC, TheCSharpAcademy requested changes

2023-01-06 19:11 UTC, TheCSharpAcademy commented on kimfom01.Console.CodingTracker/CodingTrackerConsole/UserInput.cs
> +
At the moment I can input the end date before the start date! That shouldn't be allowed 😟
![image](https://user-images.githubusercontent.com/108711476/211082574-b25f1fa8-2971-4e5c-a87e-4365dde47b01.png)

2023-01-07 08:35 UTC, kimfom01 commented
I have made a new pull request

2023-01-10 05:25 UTC, TheCSharpAcademy approved these changes
Keep in mind it's a good practice to add Ids to your models, and don't forget not to make things nullable unless they need to be. :-D

2023-01-10 05:25 UTC, merged