CodingTracker challenge project
TheCSharpAcademy/CodeReviews.Console.CodingTracker pull request #77
Opened 2024-02-25 21:19 UTC by Rxxyxd

Bit of a learning curve this one was. Let me know if i couldve done anything better:)

2024-02-26 07:07 UTC, Doc415 requested changes
Hi there. This is a good start for this project. I have marked and left comments for improvement. After you complete the changes, i ll review it again. 

ps: You can remove all uncessary usings by Code clean up in Vs
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/assets/94632226/74c705b2-a9cc-4b03-b6e1-c6da9d271694)

2024-02-26 07:07 UTC, Doc415 commented on CodingTrackerLibrary/Controller.cs
> +        public static IEnumerable<dynamic> ReadData(string connectionString)
According to the requirements you cannot return dynamic object when reading from database.
It should return
IEnumarable<Model> or List<Model> (in your case)

"When reading from the database, you can't use an anonymous object, you have to read your table into a List of Coding Sessions."

2024-02-26 17:40 UTC, Rxxyxd commented
Hows that?

2024-02-27 06:45 UTC, Doc415 requested changes
Thanks for your collabration. Your code looks much better.
Still the automatic session does not save to database. It is failing in the validation.
Take a look at the image below. 
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/assets/94632226/31f1a28d-4269-4c01-8e16-c5c6a0a04386)

2024-02-27 09:52 UTC, Doc415 approved these changes
Good to go:) nice work.

2024-03-04 18:09 UTC, closed without merging