Project Submission
TheCSharpAcademy/CodeReviews.Console.CodingTracker pull request #81
Opened 2024-03-15 19:51 UTC by obitom67

2024-03-16 15:04 UTC, Doc415 requested changes
hey there. There some unused "usings" in the code and there is an error so the code does not run. Can you fix the issue please.
![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/assets/94632226/489310fe-67fa-446f-b755-6a38ef595ee1)

2024-03-16 17:14 UTC, Doc415 requested changes
..

2024-03-18 16:20 UTC, Doc415 requested changes
You app is working fine. I marked the methods to be switched to Dapper instead of Ado.net

Suggestions:
User interface does not prompt user for invalid format input. It should be a nice touch to promt user what is going wrong.

2024-03-18 16:20 UTC, Doc415 commented on CodingTracker.obitom67/DBHandling.cs
> +                connection.Close();
He i think you are using Ado.Net here instead of Dapper. 
Can you switch to Dapper alternative for create table query please.

2024-03-18 16:20 UTC, Doc415 commented on CodingTracker.obitom67/DBHandling.cs
You are also using Ado.Net here. Please use Dapper alternative.

2024-03-18 18:55 UTC, obitom67 commented on CodingTracker.obitom67/DBHandling.cs
![03-18-24](https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/assets/27642187/ffe092fe-a567-43cb-80a6-85a38b39d9ff)

I saw this documentation for the Reader on Dapper was this so I don't know what else I should be doing for it

2024-03-18 18:58 UTC, Doc415 commented on CodingTracker.obitom67/DBHandling.cs
> ![03-18-24](https://private-user-images.githubusercontent.com/27642187/313801972-ffe092fe-a567-43cb-80a6-85a38b39d9ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODg0NzcsIm5iZiI6MTcxMDc4ODE3NywicGF0aCI6Ii8yNzY0MjE4Ny8zMTM4MDE5NzItZmZlMDkyZmUtYTU2Ny00M2NiLTgwYTYtODVhMzhiMzlkOWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE4NTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDk0YzliMDNhNDNhNDBhNjYyMGE5MTgxNTNjNTNhZGY2MTc4MGJhYWI2YzJjNDA2YmQ0MmE0M2NlMTQ5ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RuJifM6Hqf0PHW5esdDLgdjyvht_qM1_hHhNwYUa4f8)
> 
> I saw this documentation for the Reader on Dapper was this so I don't know what else I should be doing for it

![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/assets/94632226/18c9031d-3ce7-4577-bf71-66f122dac5b2)

this one is much easier with less code

2024-03-18 19:00 UTC, Doc415 commented on CodingTracker.obitom67/DBHandling.cs
> ![03-18-24](https://private-user-images.githubusercontent.com/27642187/313801972-ffe092fe-a567-43cb-80a6-85a38b39d9ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODg0NzcsIm5iZiI6MTcxMDc4ODE3NywicGF0aCI6Ii8yNzY0MjE4Ny8zMTM4MDE5NzItZmZlMDkyZmUtYTU2Ny00M2NiLTgwYTYtODVhMzhiMzlkOWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE4NTYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZDk0YzliMDNhNDNhNDBhNjYyMGE5MTgxNTNjNTNhZGY2MTc4MGJhYWI2YzJjNDA2YmQ0MmE0M2NlMTQ5ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RuJifM6Hqf0PHW5esdDLgdjyvht_qM1_hHhNwYUa4f8)
> 
> I saw this documentation for the Reader on Dapper was this so I don't know what else I should be doing for it

Try this one, much easier with less code

![image](https://github.com/TheCSharpAcademy/CodeReviews.Console.CodingTracker/assets/94632226/c7b8508f-4c9d-4f00-97b3-f23bc080a2a0)

2024-03-18 19:44 UTC, Doc415 commented
Thanks for collaboration.

2024-03-18 19:45 UTC, Doc415 approved these changes

2024-03-18 20:19 UTC, closed without merging